APP_NAME: "dominic_banking_application"
APP_PORT: 8080

DB_DRIVER: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "bank"
DB_USER: "postgres"
DB_PASSWORD: "12345"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"